In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/mpg.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

## Step 1: Inspect Missing Rows

In [4]:
df[df["horsepower"].isnull()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,europe,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl

## Step 2: Handle Missing Values

In [6]:
df = df.dropna()
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

## Step 4: Inspect Categorical Columns

In [9]:
# check unique origins

df["origin"].unique()

<StringArray>
['usa', 'japan', 'europe']
Length: 3, dtype: str

## Step 5: Remove Car Name

In [10]:
df = df.drop("name", axis=1)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

## Step 6: Encode Origin

In [11]:
# Use One-Hot Encoding

df = pd.get_dummies(
    df,
    columns=["origin"],
    drop_first=True
)

## Simple Explanation of `pd.get_dummies()` with `drop_first=True`

Imagine you have a column with **categories** (like cities, colors, countries). Machine learning models only understand **numbers**, so you need to convert these categories into numbers.

### The Problem (Without Dummies)


df = pd.DataFrame({'car': ['Toyota', 'Honda', 'BMW'], 
                   'origin': ['Japan', 'Japan', 'Germany']})

You can't give "Japan" and "Germany" directly to a model - it doesn't understand words.

### The Solution: Create Dummy Columns

`pd.get_dummies()` creates **new columns** - one for each category - with 1s and 0s:

# Without drop_first (creates 2 columns)
pd.get_dummies(df, columns=['origin'])

# Result:
#        car  origin_Japan  origin_Germany
# 0   Toyota             1               0
# 1    Honda             1               0
# 2      BMW             0               1

Now each row has:
- **1** in the column matching its origin
- **0** in all other origin columns

### What `drop_first=True` Does

It **removes one category** (the first one) to avoid being redundant:

# With drop_first=True (creates only 1 column)
pd.get_dummies(df, columns=['origin'], drop_first=True)

# Result:
#        car  origin_Germany
# 0   Toyota               0
# 1    Honda               0
# 2      BMW               1


**Notice**: We lost "origin_Japan" column. But we don't need it!

### Why Can We Drop One Column?

Because the missing column is **implied**:

- If `origin_Germany = 0` → must be Japan
- If `origin_Germany = 1` → must be Germany

The information is still there! You just saved space and avoided confusion.

## Step 7: Verify New Columns

In [12]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,18.0,8,307.0,130.0,3504,12.0,70,False,True
1,15.0,8,350.0,165.0,3693,11.5,70,False,True
2,18.0,8,318.0,150.0,3436,11.0,70,False,True
3,16.0,8,304.0,150.0,3433,12.0,70,False,True
4,17.0,8,302.0,140.0,3449,10.5,70,False,True

## Step 8: Check Data Types

In [18]:
df.info()

bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64
 7   origin_japan  392 non-null    int64
 8   origin_usa    392 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 30.6 KB

## Step 9: Separate Features and Target

In [21]:
# Target
y = df["mpg"]

# Features
X = df.drop("mpg", axis=1)

## Step 10: Verify Shapes

In [22]:
print("Features:", X.shape)
print("Target:", y.shape)

Features: (392, 8)
Target: (392,)

## Step 11: Save Clean Dataset

In [23]:
# create a clean version

df.to_csv(
    "../data/mpg_clean.csv",
    index=False
)

# Verify
pd.read_csv("../data/mpg_clean.csv").head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,18.0,8,307.0,130.0,3504,12.0,70,0,1
1,15.0,8,350.0,165.0,3693,11.5,70,0,1
2,18.0,8,318.0,150.0,3436,11.0,70,0,1
3,16.0,8,304.0,150.0,3433,12.0,70,0,1
4,17.0,8,302.0,140.0,3449,10.5,70,0,1

## Important ML Concept

At this point:

Raw Data
Missing values
Text columns
Categorical values

↓

Clean Data
No missing values
Numeric columns only
Ready for ML

This is what real-world data cleaning looks like.

In [25]:
df.shape

(392, 9)